# See https://github.com/marketplace/actions/comment-with-pytest-benchmark-result
name: Simulation Benchmark Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute benchmark
      run: |
        PYTHONPATH=. make benchmark-default

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ github.token }}
        workflow: benchmark_upload.yml
        name: benchmark_results
        path: old_benchmark
        commit: ${{github.event.pull_request.base.sha}}
      continue-on-error: true

    - name: Add benchmark to PR
      uses: nils-braun/pytest-benchmark-commenter@v2
      with:
        comparison-benchmark-file: "old_benchmark/output.json"
